eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
server:
  port: 8889
spring:
  application:
    name: ADMIN-SERVICE
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
